### ISSUE TITLE
Requirements for installation

### ISSUE THREAD

**Issue by rdoering** [shagabutdinov/sublime-local-variable#1]
Cite: "If you would like to install this package separately check "Installing packages separately" section of sublime-enhanced package."

I can't find a hint to install LocalVariable at the givin Link.

I installed the LocalVariable as single package and get an myth information about something missing without telling exactly what.

**Comment by shagabutdinov** [comment]
Follow hint "install package dependencies (listed in each package in "Dependencies sections") if any". Dependencies listed at the bottom of readme of each package.
